# Generated by Django 5.0.14 on 2025-05-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_comida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
